### ISSUE TITLE
Define registry as mandatory in the README

### ISSUE THREAD

**Issue by juanpicado** [tavvy/verdaccio-badges#3]
Using only this the plugin generates an error.

```yaml
middlewares:
  badges:
    enabled: true
```

```
error": {
    "summary": "Only HTTP(S) protocols are supported",
    "detail": ""
  }
```

The reason, this plugin is intended to be used within the Docker image and `0.0.0.0` or env variables do not exist in such an environment, while left npm installations broke. I have one suggestion here,

* let `registry.npmjs.org` by default as a fallback (not the best, since will fail (404) for private packages)
* define in the README `registry` is required by default and the user should add registry domain. 
* if env variables do not exist, then fallback to localhost 

I'm not sure what's the best here or all are not good idea. WDYT?

**Comment by tavvy** [comment]
Thanks for raising.

I've gone for a combination of the above. Having a fallback order of `custom` -> `docker env url` -> `npmjs` and made it clearer in the readme how / why you may need to set the `registry` value

Published in https://github.com/tavvy/verdaccio-badges/releases/tag/v1.1.2

**Comment by juanpicado** [comment]
Thanks @tavvy great stuff !
